-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- Teachers Table
create table teachers (
  id bigint primary key generated by default as identity,
  name text not null,
  email text not null,
  phone text,
  avatar text,
  specializations text[], -- Array of strings
  max_hours int default 20,
  current_hours int default 0,
  temp_password text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Students Table
create table students (
  id bigint primary key generated by default as identity,
  registration text not null unique,
  name text not null,
  email text not null,
  course text,
  class_group text,
  avatar text,
  temp_password text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Disciplines Table
create table disciplines (
  id bigint primary key generated by default as identity,
  code text not null,
  name text not null,
  course text,
  module text,
  hours int,
  description text,
  period text,
  assigned_teacher_id bigint references teachers(id),
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Users Table (for authentication/profile mapping if needed, though Supabase Auth handles auth users)
-- We can create a profiles table if needed, but for now relying on Supabase Auth + metadata or just mock user for the sidebar.


-- Seed Data (from mockData.ts)

insert into teachers (name, email, phone, avatar, specializations, max_hours, current_hours) values
('Ana Silva', 'ana.silva@etec.sp.gov.br', '(11) 98765-4321', 'https://lh3.googleusercontent.com/aida-public/AB6AXuASvaMsrjysEbrvfEg2c8Z02xFnujYa_IsJd_x1zGzUkZm43Y8bEHjLi3YOddCnevteVl1t55Z5uNILCrSq4FLb6Jg1L7hSd_RKaFKiZlQYCQ8FdewqB0A4H9nA7jEb1qTOSifpV61r02y-Jt2lXqSGDorHwFhBGejSpvIp8_VgbeWLeFJaG9cHl3tj1a_wgrY0-5jtibZCNcYgU4u2kYPSi7w-OP4D3CoKXeDGQDYUXQ-MjgLHmyvsjDrNC2fXLVX-LXe20lWUhh0', ARRAY['Java', 'Banco de Dados'], 20, 12),
('Carlos Oliveira', 'carlos.o@etec.sp.gov.br', '(11) 91234-5678', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCM_yNPnWFb3haLv5xeTDQR_5a4PpdOizB7fA6Jzv1hOzqUvgO8bNHXjuhwL-mthJWrSC4FXuk3Ql63kfFvgrt-uXwBFrOMi_n2BRyBLJdOZYBmL3F5ihW0RHcrIaZg2fdKiXZ95GceJIu7n73DjlW8LzWzS0AbXqFVid6Jox8ck_gZlGvOIrMRUsil0w7ZxmWboLpzvLKKSyQL0FJrRtfIgyihdr-JCiw_j571Yymbg8zw_xS7D1-kmCXKcUOkdFd0X8hjbCOxJng', ARRAY['Web', 'Design'], 40, 4),
('Maria Rita', 'maria.r@etec.sp.gov.br', '(11) 99887-7766', 'https://lh3.googleusercontent.com/aida-public/AB6AXuBqSvR-O3fD8CpBoaZWIAhfygkloV_KQuO3jgVGtipz6OKuP8cY_4D_79jO4uQ7Z6ad7G2N9If9KcSENt3okiXEkIdZtoKvAmU5BpazUMYe3rniMo8oQ514IDeaRe-cUt7QJfBcUj1EqfYMo0ii1aTQnLPsH6yFlT0qyGfqrso-fE5KouFAahnJ_AhVfPf_VkldknpV_o6K-cUdwBbixRkVvA63nIAINlDdAe2ulZpYAosI71h7X0lC0-q16v9CsmT531NdnAw55KM', ARRAY['Redes', 'Infra'], 20, 22),
('João Paulo', 'joao.p@etec.sp.gov.br', '(11) 95544-3322', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDLSkWe_RO0_tD9kM4XbjeveVovNeYor-zE2-zGRBTlJQwgeMKYRb8j7zcsLMkgpc2PPfYUglskTIZjf1VoZo2ySSwY_ppog-18mbbVF5yVfBB0t3Ml5UpWA8rWObLgJutZS5MMmOdJzN7XF6hQeglxhpVF0hSc87gyYuQxMhv8KPmyRXqriDTYtDXQwWHSyLASrc78c2clFqOZcJU54ufocRIFa7axKtG4WgkIoI24xiNvyVGxJVY0As5rtePT9cHkk5RnBgCnNbI', ARRAY['Python', 'Algoritmos'], 20, 0);

insert into students (registration, name, email, course, class_group, avatar) values
('2023058', 'Ana Souza', 'ana.souza@etec.sp.gov.br', 'Des. Sistemas', '2º Mod A', 'AS'),
('2023102', 'Carlos Mendes', 'carlos.mendes@etec.sp.gov.br', 'Administração', '1º Mod B', 'CM'),
('2023044', 'Fernanda Lima', 'fernanda.lima@etec.sp.gov.br', 'Des. Sistemas', '3º Mod A', 'FL'),
('2023150', 'Jorge Oliveira', 'jorge.o@etec.sp.gov.br', 'Des. Sistemas', '1º Mod A', 'JO'),
('2023198', 'Maria Luiza', 'maria.luiza@etec.sp.gov.br', 'Enfermagem', '2º Mod C', 'ML');

insert into disciplines (id, code, name, course, module, hours, description, period, assigned_teacher_id) values
(1024, 'LPA-101', 'Lógica de Programação', 'ds', 'Módulo 1 - Fundamentos', 80, 'Fundamentos essenciais de algoritmos.', 'Matutino', (SELECT id FROM teachers WHERE name = 'Ana Silva')),
(1025, 'SO-102', 'Sistemas Operacionais', 'ds', 'Módulo 1 - Fundamentos', 40, 'Gerenciamento de recursos e processos.', 'Matutino', null),
(2001, 'FEND-201', 'Front-End I (HTML/CSS)', 'ds', 'Módulo 2 - Desenvolvimento Web', 60, 'Estruturação e estilização web.', 'Vespertino', (SELECT id FROM teachers WHERE name = 'Carlos Oliveira')),
(2002, 'JS-202', 'JavaScript Básico', 'ds', 'Módulo 2 - Desenvolvimento Web', 60, 'Interatividade client-side.', 'Vespertino', null);

-- Enable Row Level Security (RLS) - Recommended
alter table teachers enable row level security;
alter table students enable row level security;
alter table disciplines enable row level security;

-- Create policies (open for read for now, generally need auth)
create policy "Enable read access for all users" on teachers for select using (true);
create policy "Enable insert for authenticated users only" on teachers for insert with check (auth.role() = 'authenticated' or true); -- allow anon for demo if key provided

create policy "Enable read access for all users" on students for select using (true);
create policy "Enable insert for authenticated users only" on students for insert with check (auth.role() = 'authenticated');
create policy "Enable read access for all users" on disciplines for select using (true);

-- Admins Table
create table admins (
  id bigint primary key generated by default as identity,
  email text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Seed Admin
insert into admins (email) values ('filipemenezes16@hotmail.com');

create policy "Enable read access for all users" on admins for select using (true); 
